### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by danilkuzin** [raipe/gst-bda#3]
Hi,
I am experience a possible memory leak with the bdasrc plugin (DVB-T device). I'm testing the following pipeline: bdasrc frequency=350000 ! fakesink

I'm stopping it as following:
pipeline.SetState(State.Null);
pipeline.Unref();

After starting the pipeline unmanaged memory usage increases by 10-15 MB (I'm testing it in .NET) and is not released when stopping the pipeline. Thereafter, if I continue starting/stopping pipeline, memory usage is increased by same 10-15 MB each time. Test with videotestsrc instead of bdasrc correctly releases the memory. 

Memory increases even if the tuning frequency is incorrect one (i.e. no media stream on that frequency)

**Comment by raipe** [comment]
Thank you for the bug report, there was indeed a memory leak. Queued TS samples were not released at all. This should be fixed in 20c1d8aa7f0b16422cdc6136007881a8f42d2733.

**Comment by danilkuzin** [comment]
Thank you for this fix. Unfortunately this did not fix the 10-15 MB memory increase each time. This happens if I tune to wrong frequency as well.

**Comment by raipe** [comment]
I hope this is finally fixed in eba079d2aa78124e14d0ab587558bce2197f901e. At least I can't reproduce any major memory leak any more.

**Comment by danilkuzin** [comment]
Thanks, this indeed resolves the memory issues

**Comment by raipe** [comment]
Great, thank you for verifying
